### ISSUE TITLE
Please add Russian and Ukrainian languages, they are completely translated

### ISSUE THREAD

**Issue by middle-b** [ajimix/asana-translate-chrome#29]
Please add Russian and Ukrainian languages to the extension, they are completely translated into "transifex.com"

**Comment by ajimix** [comment]
Hey @middle-b the problem with the extension is that Asana updated the interface recently, therefore most of the translations stopped working so there is no point in adding the translated strings. 
If you want you can update the code of the extension to support the new Asana interface. Meanwhile I'm closing this issue.
